### ISSUE TITLE
Uploading Photos

### ISSUE THREAD

**Issue by kmichael500** [kmichael500/planarian#9]
Uploading photos works if there is a single image. However, when multiple are uploaded the list is empty. The route value for the ID is also null so I'm not sure how it's even activating the route.

However, occasionally it works.

My guess is it's some type of binding issue.

**Comment by Greenman126** [comment]
I was just able to upload 3 photos at the same time and it worked.

I'll suggest adding a "nearest station" field for photos submitted

**Comment by Greenman126** [comment]
@kmichael500 this appears to be resolved.
